// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ8I_snxaJ7pj4nsYkszmPkERP5yDRRsk',
    appId: '1:234577028209:web:e2f8ee7727cb4d110aa7d0',
    messagingSenderId: '234577028209',
    projectId: 'foodchi-41cf2',
    authDomain: 'foodchi-41cf2.firebaseapp.com',
    storageBucket: 'foodchi-41cf2.firebasestorage.app',
    measurementId: 'G-09HPJQVD9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA01oumOZWb_CDI-bqQlI70oc5oBMf5gY4',
    appId: '1:234577028209:android:708700e5396e47c30aa7d0',
    messagingSenderId: '234577028209',
    projectId: 'foodchi-41cf2',
    storageBucket: 'foodchi-41cf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAryUi_NZ6uGWGojpyd2MlZbJEZ0jXnL3Q',
    appId: '1:234577028209:ios:2beb48c86d739e2f0aa7d0',
    messagingSenderId: '234577028209',
    projectId: 'foodchi-41cf2',
    storageBucket: 'foodchi-41cf2.firebasestorage.app',
    iosClientId: '234577028209-oq28qorsaafr9fpsb798l89dphcomnln.apps.googleusercontent.com',
    iosBundleId: 'com.pedalchi.foodchi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAryUi_NZ6uGWGojpyd2MlZbJEZ0jXnL3Q',
    appId: '1:234577028209:ios:2beb48c86d739e2f0aa7d0',
    messagingSenderId: '234577028209',
    projectId: 'foodchi-41cf2',
    storageBucket: 'foodchi-41cf2.firebasestorage.app',
    iosClientId: '234577028209-oq28qorsaafr9fpsb798l89dphcomnln.apps.googleusercontent.com',
    iosBundleId: 'com.pedalchi.foodchi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ8I_snxaJ7pj4nsYkszmPkERP5yDRRsk',
    appId: '1:234577028209:web:028b1f1b515dfa950aa7d0',
    messagingSenderId: '234577028209',
    projectId: 'foodchi-41cf2',
    authDomain: 'foodchi-41cf2.firebaseapp.com',
    storageBucket: 'foodchi-41cf2.firebasestorage.app',
    measurementId: 'G-J3GLFZHXMJ',
  );
}
